"""Conservative sheet cleanup policy for EngiTools CAD outputs.

The policy is deliberately preservation-first.  It may remove only entities that
are positively identified as stale sheet/presentation artifacts.  Architectural
geometry is never removed merely because it lies in a footer/subtitle region.

This module is project-agnostic and is safe to run on every generated plan sheet
before final QA.
"""

from dataclasses import dataclass
from typing import Optional


PLAN_FAMILIES = {
    "ROOF",
    "SANITARY_VENT",
    "WATER",
    "HEATING",
    "GAS",
    "SPLIT_AC",
    "SPLIT_ROOF",
    "EXHAUST",
}

# Layers that were observed to carry old sheet-decoration/footer material in the
# benchmark drawings.  Membership is NOT sufficient for deletion by itself;
# entity type/text shape must also match a low-risk presentation artifact.
KNOWN_LEGACY_FOOTER_LAYERS = {
    "EL2",
    "MEN",
    "construction",
    "suport",
    "support",
    "f n",
    "DAM--PLAN",
}

# Anything generated by EngiTools is always preserved here; its own QA may later
# decide whether to replace/regenerate it.
PRESERVE_PREFIXES = ("ENGITOOLS-",)

# Common architecture-semantic layers.  This is only an extra safety net; the
# default behaviour is preserve, so unknown layers are preserved as well.
PRESERVE_ARCH_LAYERS = {
    "0",
    "WALL",
    "DOOR",
    "WINDOW",
    "OPENING",
    "SHAFT",
    "COLUMN",
    "GRID",
    "AXIS",
    "STAIR",
    "RAMP",
    "SLAB",
    "STRUCTURE",
    "DIMENSION",
}

# Stale imported sheet labels that are safe to remove when they occur in the
# reserved footer/subtitle band.  They are presentation metadata, not building
# geometry.
STALE_TEXT_MARKERS = (
    "پلان معماری",
    "Arc -",
    "DETAIL REFERENCES:",
)


@dataclass(frozen=True)
class FooterCleanupBand:
    """Footer cleanup band relative to owning sheet model bounds."""

    y1_offset: float = 5.55
    y2_offset: float = 8.65
    x_inset: float = 0.80


def _in_band(*, x: float, y: float, sheet_bounds, band: FooterCleanupBand) -> bool:
    x1, y1, x2, _ = sheet_bounds
    return (
        x1 + band.x_inset <= x <= x2 - band.x_inset
        and y1 + band.y1_offset <= y <= y1 + band.y2_offset
    )


def should_remove_footer_entity(
    *,
    family: str,
    layer: str,
    entity_type: str,
    bbox_center_x: float,
    bbox_center_y: float,
    bbox_width: float,
    bbox_height: float,
    sheet_bounds: tuple[float, float, float, float],
    text: Optional[str] = None,
    band: FooterCleanupBand = FooterCleanupBand(),
) -> bool:
    """Return True only for confidently identified stale footer artifacts.

    Preservation contract:
    - never remove entities outside the reserved band;
    - never remove EngiTools-generated entities;
    - never remove architectural geometry by region alone;
    - never remove DIMENSION/HATCH/INSERT/SOLID/ARC/CIRCLE based only on layer;
    - unknown layers default to PRESERVE;
    - line/polyline deletion is limited to thin separator-like geometry on an
      explicitly known legacy presentation layer.
    """

    if family not in PLAN_FAMILIES:
        return False

    layer = str(layer or "")
    et = str(entity_type or "").upper()
    txt = (text or "").strip()

    if layer.startswith(PRESERVE_PREFIXES):
        return False

    if not _in_band(
        x=bbox_center_x,
        y=bbox_center_y,
        sheet_bounds=sheet_bounds,
        band=band,
    ):
        return False

    # Text is removable only when it is a positively identified stale sheet
    # label.  Generic architectural notes/dimensions are preserved.
    if et in {"TEXT", "MTEXT"}:
        return any(marker in txt for marker in STALE_TEXT_MARKERS)

    # Architectural and semantic layers are always protected.
    if layer.upper() in {x.upper() for x in PRESERVE_ARCH_LAYERS}:
        return False

    # Never delete semantic/compound entity types without a dedicated classifier.
    if et in {"DIMENSION", "INSERT", "HATCH", "SOLID", "ARC", "CIRCLE", "ELLIPSE", "SPLINE"}:
        return False

    # Low-risk stale separator strokes: only on an explicitly known legacy layer,
    # only thin line-like geometry, and only inside the reserved subtitle band.
    if layer in KNOWN_LEGACY_FOOTER_LAYERS:
        if et == "LINE":
            thin = min(abs(bbox_width), abs(bbox_height)) <= 0.10
            longish = max(abs(bbox_width), abs(bbox_height)) >= 0.70
            return thin and longish
        if et in {"LWPOLYLINE", "POLYLINE"}:
            thin = abs(bbox_height) <= 0.12 or abs(bbox_width) <= 0.12
            longish = max(abs(bbox_width), abs(bbox_height)) >= 0.70
            return thin and longish

    # Default is always preserve.
    return False


def qa_footer_band_clean(remaining_legacy_count: int, generated_subtitle_count: int) -> bool:
    """Final QA gate for every plan sheet."""
    return remaining_legacy_count == 0 and generated_subtitle_count >= 2
